CREATE DATABASE FTT
GO
USE FTT
GO
CREATE TABLE Pokemon (
	Id INTEGER IDENTITY PRIMARY KEY,
	Name VARCHAR,
    Number INTEGER,
    Type VARCHAR
)
GO
CREATE TABLE Type (
	Id INTEGER IDENTITY PRIMARY KEY,
    Name VARCHAR,
    Biggest_Weakness VARCHAR,
    Biggest_Advantage VARCHAR
)
GO
CREATE TABLE Moves (
    Id INTEGER IDENTITY PRIMARY KEY,
    Name VARCHAR,
    Power INTEGER,
    Acuracy INTEGER,
    Type INTEGER,
)
GO
CREATE TABLE Berry (
	Id INTEGER IDENTITY PRIMARY KEY,
    Name VARCHAR,
    Growth_Time INTEGER
)
GO
CREATE TABLE Item (
    Id INTEGER IDENTITY PRIMARY KEY,
    Name VARCHAR,
    Rarity INTEGER
)